[package]
name = "utente"
version = "0.1.1"
authors = ["Nick Logozzo <nlogozzo225@gmail.com>"]
edition = "2024"
build = "build.rs"
readme = "README.md"
license = "MIT"
description = "A cross-platform library for gathering user information."
repository = "https://github.com/NickvisionApps/utente"
keywords = ["user", "username", "account", "cross-platform"]
categories = ["os"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_NetManagement",
    "Win32_Security",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Authorization",
    "Win32_System_WindowsProgramming",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation = "0.3"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
